---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-mirrored-pair-volume.html 
sidebar: sidebar 
keywords: change, settings, mirrored, pair, volume, adjust, percentage, point, system, manager, alert, notification, reserved, capacity, full 
summary: È possibile modificare le impostazioni di un volume di coppia mirrorata per regolare il punto percentuale in cui System Manager invia una notifica di avviso quando la capacità riservata per un volume di coppia mirrorata è quasi piena. 
---
= Modificare le impostazioni di capacità riservata per un volume di coppia mirrorata
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare le impostazioni di un volume di coppia mirrorata per regolare il punto percentuale in cui System Manager invia una notifica di avviso quando la capacità riservata per un volume di coppia mirrorata è quasi piena.

.Fasi
. Selezionare menu:Storage[Pools & Volume Groups] (Storage[Pools & Volume Groups])
. Selezionare la scheda *capacità riservata*.
. Selezionare il volume della coppia mirrorata che si desidera modificare, quindi fare clic su *Visualizza/Modifica impostazioni*.
+
Viene visualizzata la finestra di dialogo *Mirrored Pair Volume Reserved Capacity Settings*.

. Modificare le impostazioni di capacità riservata per il volume di coppia mirrorata in base alle esigenze.
+
.Dettagli campo
[%collapsible]
====
[cols="1a,3a"]
|===
| Impostazione | Descrizione 


 a| 
Avvisami quando...
 a| 
Utilizzare la casella di selezione per regolare il punto percentuale in cui System Manager invia una notifica di avviso quando la capacità riservata per una coppia mirrorata è quasi piena.

Quando la capacità riservata per la coppia mirrorata supera la soglia specificata, System Manager invia un avviso, consentendo di aumentare la capacità riservata.


NOTE: La modifica dell'impostazione Avviso per una coppia mirrorata modifica l'impostazione Avviso per tutte le coppie mirrorate che appartengono allo stesso gruppo di coerenza mirror.



 a| 
Policy per la capacità massima riservata
 a| 
È possibile scegliere una delle seguenti policy:

** *Rimuovi immagine snapshot meno recente* – System Manager rimuove automaticamente l'immagine snapshot meno recente nel gruppo di coerenza, che rilascia la capacità riservata del membro per il riutilizzo all'interno del gruppo.
** *Rifiuta scritture nel volume base* – quando la capacità riservata raggiunge la massima percentuale definita, System Manager rifiuta qualsiasi richiesta di scrittura i/o nel volume base che ha attivato l'accesso alla capacità riservata.


|===
====
. Fare clic su *Save* (Salva) per applicare le modifiche.


.Risultato
System Manager modifica le impostazioni di capacità riservata per il volume membro, nonché le impostazioni di capacità riservata per tutti i volumi membro del gruppo di coerenza.
