---
permalink: sm-storage/functional-comparison-of-pools-and-volume-groups.html 
sidebar: sidebar 
keywords: function, purpose, pool, volume, group, same, objects, set, drives, logically, together, storage, array, create, host, access 
summary: La funzione e lo scopo di un pool e di un gruppo di volumi sono identici. Entrambi gli oggetti sono un insieme di dischi raggruppati logicamente in un array di storage e vengono utilizzati per creare volumi ai quali un host può accedere. 
---
= Confronto funzionale di pool e gruppi di volumi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La funzione e lo scopo di un pool e di un gruppo di volumi sono identici. Entrambi gli oggetti sono un insieme di dischi raggruppati logicamente in un array di storage e vengono utilizzati per creare volumi ai quali un host può accedere.

La seguente tabella consente di decidere se un pool o un gruppo di volumi si adatta meglio alle proprie esigenze di storage.

[cols="3*""]
|===
| Funzione | Piscina | Gruppo di volumi 


 a| 
Supporto di diversi livelli RAID
 a| 
No Sempre RAID 6.
 a| 
Sì. RAID 0, 1, 10, 5 e 6 disponibili.



 a| 
Supporto di thin volumi
 a| 
Sì
 a| 
No



 a| 
Crittografia completa del disco (FDE) supportata
 a| 
Sì
 a| 
Sì



 a| 
Data Assurance (da) supportato
 a| 
Sì
 a| 
Sì



 a| 
Protezione contro la perdita di shelf supportata
 a| 
Sì
 a| 
Sì



 a| 
Protezione contro le perdite di cassetto supportata
 a| 
Sì
 a| 
Sì



 a| 
Supporto di velocità di dischi miste
 a| 
Consigliato per essere lo stesso, ma non richiesto. Il disco più lento determina la velocità di tutti i dischi.
 a| 
Consigliato per essere lo stesso, ma non richiesto. Il disco più lento determina la velocità di tutti i dischi.



 a| 
Capacità di dischi misti supportata
 a| 
Consigliato per essere lo stesso, ma non richiesto. Il disco più piccolo determina la capacità di tutti i dischi.
 a| 
Consigliato per essere lo stesso, ma non richiesto. Il disco più piccolo determina la capacità di tutti i dischi.



 a| 
Numero minimo di dischi
 a| 
11
 a| 
Dipende dal livello RAID. RAID 0 richiede 1. RAID 1 o 10 richiede 2 (richiede un numero pari). RAID 5 è minimo 3. RAID 6 è minimo 5.



 a| 
Numero massimo di dischi
 a| 
Fino al limite massimo per lo storage array
 a| 
RAID 1 e 10 - fino al limite massimo di dischi RAID 5, 6-30 dello storage array



 a| 
Possibilità di scegliere singoli dischi durante la creazione di un volume
 a| 
No
 a| 
Sì



 a| 
Può specificare le dimensioni del segmento durante la creazione di un volume
 a| 
Sì. 128K supportato.
 a| 
Sì



 a| 
Consente di specificare le caratteristiche di i/o durante la creazione di un volume
 a| 
No
 a| 
Sì. Supporto di file system, database, contenuti multimediali e personalizzati.



 a| 
Protezione dai guasti del disco
 a| 
Utilizza la capacità di conservazione su ogni disco del pool, rendendo più rapida la ricostruzione.
 a| 
Utilizza un disco hot spare. La ricostruzione è limitata dagli IOPS del disco.



 a| 
Avviso quando si raggiunge il limite di capacità
 a| 
Sì. Può impostare un avviso quando la capacità utilizzata raggiunge una percentuale della capacità massima.
 a| 
No



 a| 
Migrazione a un array storage diverso supportata
 a| 
No Richiede prima la migrazione a un gruppo di volumi.
 a| 
Sì



 a| 
Dimensione dinamica dei segmenti (DSS)
 a| 
No
 a| 
Sì



 a| 
Può modificare il livello RAID
 a| 
No
 a| 
Sì



 a| 
Espansione dei volumi (aumento della capacità)
 a| 
Sì
 a| 
Sì



 a| 
Espansione della capacità (aggiunta di capacità)
 a| 
Sì
 a| 
Sì



 a| 
Riduzione della capacità
 a| 
Sì
 a| 
No

|===
[NOTE]
====
I tipi di dischi misti (HDD, SSD) non sono supportati per pool o gruppi di volumi.

====