---
permalink: sm-interface/administrator-password-protection.html 
sidebar: sidebar 
keywords: configure, storage, array, administrator, password, protect, unauthorize, access 
summary: È necessario configurare lo storage array con una password di amministratore per proteggerlo da accessi non autorizzati. 
---
= Protezione con password di amministratore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario configurare lo storage array con una password di amministratore per proteggerlo da accessi non autorizzati.



== Impostazione di una password amministratore

L'impostazione di una password di amministratore per lo storage array protegge l'IT dagli utenti che eseguono comandi distruttivi inconsapevolmente o maliziosamente. Quando si avvia System Manager per la prima volta, viene richiesto di impostare una password di amministratore.

Esiste una password di amministratore condivisa tra tutti gli utenti. Qualsiasi utente in possesso di questa password può apportare modifiche alla configurazione dell'array di storage, ad esempio l'aggiunta, la modifica o la rimozione di oggetti o impostazioni.



== Immissione della password

Il sistema richiede la password una sola volta durante una singola sessione di gestione. Una sessione scade dopo 20 minuti di inattività. A questo punto, è necessario immettere nuovamente la password.

Se un altro utente che gestisce lo stesso array di storage da un altro client di gestione modifica la password durante la sessione, viene richiesta una password la volta successiva che si tenta di eseguire un'operazione di configurazione o un'operazione di visualizzazione.

Per motivi di sicurezza, è possibile tentare di inserire una password solo cinque volte prima che lo storage array entri in uno stato di "blocco". In questo stato, lo storage array rifiuterà i successivi tentativi di password. Prima di inserire nuovamente una password, attendere 10 minuti per ripristinare lo stato "normale" dello storage array.



== Rimozione dei dischi con protezione tramite password

La password viene memorizzata in un'area riservata di ciascun disco dello storage array. Se si rimuovono tutte le unità da un array di storage, la password non funzionerà più. Per correggere questa condizione, reinstallare uno dei dischi originali nell'array di storage.



== Rimozione della protezione tramite password

Se non si desidera più avere comandi protetti da password, inserire la password corrente dell'amministratore e lasciare vuote le caselle di testo della nuova password.

[NOTE]
====
L'esecuzione di comandi di configurazione su un array di storage può causare gravi danni, inclusa la perdita di dati. Per questo motivo, è necessario impostare sempre una password di amministratore per lo storage array. Utilizzare una password di amministratore lunga con almeno 15 caratteri alfanumerici per aumentare la protezione.

====