---
permalink: sm-settings/configure-snmp-alerts.html 
sidebar: sidebar 
keywords: configuration, snmp alerts, identification, one server, storage array, snmp traps, community name, ip address 
summary: 'Per configurare gli avvisi SNMP (Simple Network Management Protocol), è necessario identificare almeno un server in cui il monitor degli eventi dell"array di storage può inviare trap SNMP. La configurazione richiede un nome di comunità e un indirizzo IP per il server.' 
---
= Configurare comunità e destinazioni per gli avvisi SNMP
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per configurare gli avvisi SNMP (Simple Network Management Protocol), è necessario identificare almeno un server in cui il monitor degli eventi dell'array di storage può inviare trap SNMP. La configurazione richiede un nome di comunità e un indirizzo IP per il server.

.Prima di iniziare
* Un server di rete deve essere configurato con un'applicazione di servizio SNMP. È necessario l'indirizzo di rete di questo server (un indirizzo IPv4 o IPv6), in modo che il monitor eventi possa inviare messaggi trap a tale indirizzo. È possibile utilizzare più di un server (sono consentiti fino a 10 server).
* È necessario creare un nome di comunità composto solo da caratteri ASCII stampabili. Il nome di comunità, che è una stringa che agisce come una password per i server di rete, viene in genere creato da un amministratore di rete. È possibile creare fino a 256 community.
* Il file MIB (Management Information base) è stato copiato e compilato sul server con l'applicazione del servizio SNMP. Questo file MIB definisce i dati monitorati e gestiti.
+
Se non si dispone del file MIB, è possibile ottenerlo dal sito NetApp Support:

+
** Passare a. https://mysupport.netapp.com/site/["Supporto NetApp"^].
** Fare clic su *Downloads*.
** Fare clic su *Software*.
** Individuare il software di gestione (ad esempio, Gestore di sistema di SANtricity), quindi fare clic su *Go!* (Vai) a destra.
** Fare clic su**View & Download** (Visualizza e scarica) sulla versione più recente.
** Fare clic su *continua* nella parte inferiore della pagina.
** Accettare l'EULA.
** Scorrere verso il basso fino a visualizzare *MIB file for SNMP trap*, quindi fare clic sul collegamento per scaricare il file.




.A proposito di questa attività
Questa attività descrive come identificare il server SNMP per le destinazioni trap, quindi verificare la configurazione.

.Fasi
. Selezionare *menu:Impostazioni[Avvisi]*.
. Selezionare la scheda *SNMP*.
+
Se una community non è ancora configurata, nella scheda SNMP viene visualizzato "Configure Communities" (Configura community).

. Selezionare *Configura community*.
+
Viene visualizzata la finestra di dialogo *Configura comunità*.

. Nel campo *Nome comunità*, immettere una o più stringhe di comunità per i server di rete, quindi fare clic su *Salva*.
+
Nella pagina Avvisi viene visualizzato "Add Trap Destinations" (Aggiungi destinazioni trap).

. Selezionare *Add Trap Destinations* (Aggiungi destinazioni trap).
+
Viene visualizzata la finestra di dialogo *Add Trap Destinations* (Aggiungi destinazioni trap).

. Inserire una o più destinazioni trap, selezionare i nomi di comunità associati, quindi fare clic su *Aggiungi*.
+
** *Destinazione trap* -- immettere un indirizzo IPv4 o IPv6 del server che esegue un servizio SNMP.
** *Nome di comunità* -- dal menu a discesa, selezionare il nome di comunità per questa destinazione trap. (Se è stato definito un solo nome di comunità, il nome viene già visualizzato in questo campo).
** *Send Authentication Failure Trap* -- selezionare questa opzione (la casella di controllo) se si desidera avvisare la destinazione della trap ogni volta che una richiesta SNMP viene rifiutata a causa di un nome di comunità non riconosciuto. Dopo aver fatto clic su *Aggiungi*, le destinazioni trap e i nomi di comunità associati vengono visualizzati nella scheda *SNMP* della pagina *Avvisi*.


. Per assicurarsi che un trap sia valido, selezionare una destinazione trap dalla tabella, quindi fare clic su *Test Trap Destination* (destinazione trap test) per inviare un trap di test all'indirizzo configurato.


.Risultati
Il monitor degli eventi invia trap SNMP ai server ogni volta che si verifica un evento verificabile.
