---
permalink: sm-settings/configure-snmp-mib-variables.html 
sidebar: sidebar 
keywords: snmp alerts, optional, mib, variables, snmp traps, storage array, contact person 
summary: 'Per gli avvisi SNMP, è possibile configurare facoltativamente le variabili MIB (Management Information base) che vengono visualizzate nei trap SNMP. Queste variabili possono restituire il nome dell"array di storage, la posizione dell"array e una persona di contatto.' 
---
= Configurare le variabili SNMP MIB
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per gli avvisi SNMP, è possibile configurare facoltativamente le variabili MIB (Management Information base) che vengono visualizzate nei trap SNMP. Queste variabili possono restituire il nome dell'array di storage, la posizione dell'array e una persona di contatto.

.Prima di iniziare
Il file MIB deve essere copiato e compilato sul server con l'applicazione di servizio SNMP.

Se non si dispone di un file MIB, è possibile ottenerlo come segue:

* Passare a. https://mysupport.netapp.com/site/["Supporto NetApp"^].
* Fare clic su *Downloads*.
* Fare clic su *Software*.
* Individuare il software di gestione (ad esempio, Gestore di sistema di SANtricity), quindi fare clic su *Go!* (Vai) a destra.
* Fare clic su *View & Download* (Visualizza e scarica) nella versione più recente.
* Fare clic su *continua* nella parte inferiore della pagina.
* Accettare l'EULA.
* Scorrere verso il basso fino a visualizzare *MIB file for SNMP trap*, quindi fare clic sul collegamento per scaricare il file.


.A proposito di questa attività
Questa attività descrive come definire le variabili MIB per i trap SNMP. Queste variabili possono restituire i seguenti valori in risposta a SNMP GetRequests:

* `_sysName_` (nome dell'array di storage)
* `_sysLocation_` (posizione dello storage array)
* `_sysContact_` (nome di un amministratore)


.Fasi
. Selezionare *menu:Impostazioni[Avvisi]*.
. Selezionare la scheda *SNMP*.
. Selezionare *Configure SNMP MIB variables* (Configura variabili SNMP MIB).
+
Viene visualizzata la finestra di dialogo Configura variabili MIB SNMP.

. Immettere uno o più dei seguenti valori, quindi fare clic su *Save* (Salva).
+
** *Name* -- il valore per la variabile MIB `_sysName_`. Ad esempio, inserire un nome per l'array di storage.
** *Location* -- il valore della variabile MIB `_sysLocation_`. Ad esempio, inserire una posizione dell'array di storage.
** *Contatto* -- il valore della variabile MIB `_sysContact_`. Ad esempio, inserire un amministratore responsabile dello storage array.




.Risultati
Questi valori vengono visualizzati nei messaggi trap SNMP per gli avvisi degli array di storage.
