---
permalink: sm-settings/what-do-i-need-to-know-before-unlocking-secure-drives.html 
sidebar: sidebar 
keywords: unlock, data, secure, enable, migration, storage array, import, security, key 
summary: Per sbloccare i dati da un disco abilitato alla protezione che viene migrato a un nuovo array di storage, è necessario importare la chiave di sicurezza. 
---
= Cosa devo sapere prima di sbloccare dischi sicuri?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per sbloccare i dati da un disco abilitato alla protezione che viene migrato a un nuovo array di storage, è necessario importare la chiave di sicurezza.

Prima di sbloccare dischi sicuri, tenere presenti le seguenti linee guida:

* L'array di storage di destinazione (in cui si spostano i dischi) deve disporre già di una chiave di sicurezza. I dischi migrati verranno ridimitati nell'array di storage di destinazione.
* Per i dischi che si stanno migrando, si conoscono l'identificatore della chiave di sicurezza e la password che corrisponde al file della chiave di sicurezza.
* Il file della chiave di sicurezza è disponibile sul client di gestione (il sistema con un browser utilizzato per accedere a System Manager).
* Se si sta reimpostando un disco NVMe bloccato, è necessario inserire l'ID di sicurezza del disco. Per individuare l'ID di sicurezza, rimuovere fisicamente l'unità e individuare la stringa PSID (massimo 32 caratteri) sull'etichetta dell'unità. Assicurarsi che il disco sia reinstallato prima di avviare l'operazione.

