---
permalink: sm-support/critical-events.html 
sidebar: sidebar 
keywords: critical, events, indicate, problem, storage, array, resolve, immediately, might, prevent, loss, data, access 
summary: 'Gli eventi critici indicano un problema con lo storage array. Se si risolve immediatamente l"evento critico, si potrebbe evitare la perdita di accesso ai dati.' 
---
= Eventi critici
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gli eventi critici indicano un problema con lo storage array. Se si risolve immediatamente l'evento critico, si potrebbe evitare la perdita di accesso ai dati.

Quando si verifica un evento critico, questo viene registrato nel registro eventi. Tutti gli eventi critici vengono inviati alla console di gestione SNMP o al destinatario dell'e-mail configurato per la ricezione delle notifiche di avviso. Se l'ID dello shelf non è noto al momento dell'evento, l'ID dello shelf viene elencato come "Shelf unknown".

Quando si riceve un evento critico, fare riferimento alla procedura Recovery Guru per una descrizione dettagliata dell'evento critico. Completare la procedura Recovery Guru per correggere l'evento critico. Per correggere alcuni eventi critici, potrebbe essere necessario contattare il supporto tecnico.
