---
permalink: sm-support/drive-firmware-upgrades.html 
sidebar: sidebar 
keywords: drive, firmware, control, low, level, operating, characteristics, periodically, manufacturer, release, update, add, new, features, improve, performance, fix, detects 
summary: Il firmware del disco controlla le caratteristiche operative di basso livello di un disco. Periodicamente, i produttori di dischi rilasciano aggiornamenti al firmware del disco per aggiungere nuove funzionalità, migliorare le prestazioni e correggere i difetti. 
---
= Aggiornamenti del firmware del disco
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il firmware del disco controlla le caratteristiche operative di basso livello di un disco. Periodicamente, i produttori di dischi rilasciano aggiornamenti al firmware del disco per aggiungere nuove funzionalità, migliorare le prestazioni e correggere i difetti.



== Aggiornamenti del firmware del disco online e offline

Esistono due tipi di metodi di aggiornamento del firmware del disco: Online e offline.



== Online

Durante un aggiornamento online, i dischi vengono aggiornati in sequenza, uno alla volta. Lo storage array continua l'elaborazione dell'i/o durante l'aggiornamento. Non è necessario interrompere l'i/O. Se un disco è in grado di eseguire un aggiornamento online, il metodo online viene utilizzato automaticamente.

I dischi che possono eseguire un aggiornamento online includono:

* Dischi in un pool ottimale
* Dischi in un gruppo ottimale di volumi ridondanti (RAID 1, RAID 5 e RAID 6)
* Dischi non assegnati
* Dischi hot spare in standby


L'aggiornamento del firmware di un disco online può richiedere diverse ore per esporre l'array di storage a potenziali errori di volume. In questi casi si potrebbero verificare errori di volume:

* In un gruppo di volumi RAID 1 o RAID 5, un disco si guasta mentre viene aggiornato un altro disco del gruppo di volumi.
* In un pool o gruppo di volumi RAID 6, due dischi si guastano mentre viene aggiornato un altro disco del pool o gruppo di volumi.




== Offline (parallelo)

Durante un aggiornamento offline, tutti i dischi dello stesso tipo di disco vengono aggiornati contemporaneamente. Questo metodo richiede l'interruzione dell'attività di i/o nei volumi associati ai dischi selezionati. Poiché è possibile aggiornare più dischi contemporaneamente (in parallelo), il downtime complessivo è notevolmente ridotto. Se un disco può eseguire solo un aggiornamento offline, il metodo offline viene utilizzato automaticamente.

I seguenti dischi DEVONO utilizzare il metodo offline:

* Dischi in un gruppo di volumi non ridondante (RAID 0)
* Dischi in un pool o un gruppo di volumi non ottimali
* Dischi nella cache SSD




== Compatibilità

Ciascun file del firmware del disco contiene informazioni sul tipo di disco su cui viene eseguito il firmware. È possibile scaricare il file del firmware specificato solo su un'unità compatibile. System Manager verifica automaticamente la compatibilità durante il processo di aggiornamento.
