---
permalink: um-certificates/use-ca-signed-certificate-um.html 
sidebar: sidebar 
keywords: ca certificate, secure, access, management, system, unified manager 
summary: È possibile ottenere e importare certificati firmati dalla CA per un accesso sicuro al sistema di gestione che ospita Unified Manager. 
---
= USA certificati firmati dalla CA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile ottenere e importare certificati firmati dalla CA per un accesso sicuro al sistema di gestione che ospita Unified Manager.

.Prima di iniziare
* È necessario effettuare l'accesso con un profilo utente che includa le autorizzazioni di amministratore di sicurezza. In caso contrario, le funzioni del certificato non vengono visualizzate.


.A proposito di questa attività
L'utilizzo dei certificati firmati dalla CA è una procedura in due fasi.



== Fase 1: Completare e inviare una CSR

È necessario innanzitutto generare un file CSR (Certificate Signing Request) e inviarlo alla CA.

.Prima di iniziare
* È necessario effettuare l'accesso con un profilo utente che includa le autorizzazioni di amministratore di sicurezza. In caso contrario, le funzioni del certificato non vengono visualizzate.


.A proposito di questa attività
Questa attività descrive come generare il file CSR inviato a una CA per ricevere certificati di gestione firmati per il sistema che ospita Unified Manager e Web Services Proxy. È necessario fornire informazioni sull'organizzazione, oltre all'indirizzo IP o al nome DNS del sistema host.

[CAUTION]
====
Non generare una nuova CSR dopo l'invio alla CA. Quando si genera una CSR, il sistema crea una coppia di chiavi private e pubbliche. La chiave pubblica fa parte della CSR, mentre la chiave privata viene conservata nell'archivio chiavi. Quando si ricevono i certificati firmati e li si importano nel keystore, il sistema garantisce che sia le chiavi private che quelle pubbliche siano la coppia originale. Pertanto, non è necessario generare una nuova CSR dopo averla inoltrata alla CA. In tal caso, i controller generano nuove chiavi e i certificati ricevuti dalla CA non funzioneranno.

====
.Fasi
. Selezionare *Certificate Management* (Gestione certificati).
. Dalla scheda *Gestione*, selezionare *completa CSR*.
. Inserire le seguenti informazioni, quindi fare clic su *Avanti*:
+
** *Organizzazione* -- il nome completo e legale della tua azienda o organizzazione. Includere i suffissi, ad esempio Inc. O Corp.
** *Unità organizzativa (opzionale)* -- la divisione dell'organizzazione che gestisce il certificato.
** *Città/Località* -- la città in cui si trova il sistema host o l'azienda.
** *Stato/Regione (opzionale)* -- Stato o regione in cui si trova il sistema host o l'azienda.
** *Codice ISO del Paese* -- Codice ISO (International Organization for Standardization) a due cifre del Paese, ad esempio USA.


. Inserire le seguenti informazioni relative al sistema host:
+
** *Nome comune* -- Indirizzo IP o nome DNS del sistema host in cui è installato il proxy dei servizi Web. Assicurarsi che l'indirizzo sia corretto; deve corrispondere esattamente a quello immesso per accedere a Unified Manager nel browser. Non includere http:// o https://.
** *Indirizzi IP alternativi* -- se il nome comune è un indirizzo IP, è possibile inserire eventuali indirizzi IP o alias aggiuntivi per il sistema host. Per più voci, utilizzare un formato delimitato da virgole.
** *Nomi DNS alternativi* -- se il nome comune è un nome DNS, immettere eventuali nomi DNS aggiuntivi per il sistema host. Per più voci, utilizzare un formato delimitato da virgole. Se non sono presenti nomi DNS alternativi, ma è stato immesso un nome DNS nel primo campo, copiarlo qui.


. Fare clic su *fine*.
+
Un file CSR viene scaricato nel sistema locale. La posizione della cartella del download dipende dal browser in uso.

. Inviare il file CSR a una CA e richiedere certificati firmati in formato PEM o DER.


.Al termine
Attendere che la CA restituisca i file di certificato, quindi passare a. link:step-3-import-management-certificates-unified.html["Fase 2: Importazione dei certificati di gestione"].



== Fase 2: Importazione dei certificati di gestione

Una volta ricevuti i certificati firmati, importare la catena di certificati per il sistema host in cui è installata l'interfaccia di Unified Manager.

.Prima di iniziare
* È necessario effettuare l'accesso con un profilo utente che includa le autorizzazioni di amministratore di sicurezza. In caso contrario, le funzioni del certificato non vengono visualizzate.
* È stata generata una richiesta di firma del certificato (file CSR) e inviata alla CA.
* La CA ha restituito file di certificato attendibili.
* I file dei certificati vengono installati nel sistema locale.
* Se la CA ha fornito un certificato concatenato (ad esempio, un file .p7b), è necessario decomprimere il file concatenato in singoli file: Il certificato root, uno o più certificati intermedi e il certificato del server. È possibile utilizzare Windows `certmgr` Utility per disimballare i file (fare clic con il pulsante destro del mouse e selezionare *menu:tutte le attività[Esporta]*). Una volta completate le esportazioni, viene visualizzato un file CER per ciascun file di certificato nella catena.


.Fasi
. Selezionare *Certificate Management* (Gestione certificati).
. Dalla scheda *Gestione*, selezionare *Importa*.
+
Viene visualizzata una finestra di dialogo per l'importazione dei file dei certificati.

. Fare clic su *Browse* (Sfoglia) per selezionare prima i file root e intermedi, quindi selezionare il certificato del server.
+
I nomi dei file vengono visualizzati nella finestra di dialogo.

. Fare clic su *Importa*.


.Risultati
I file vengono caricati e validati. Le informazioni sul certificato vengono visualizzate nella pagina Gestione certificati.
