---
permalink: um-certificates/why-cant-i-log-in-unified.html 
sidebar: sidebar 
keywords: receive, error, attempt, santricity, unified, manager, causes 
summary: Se si riceve un errore durante il tentativo di accesso a Gestione unificata di SANtricity, esaminare queste possibili cause. 
---
= Perché non riesco ad accedere?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si riceve un errore durante il tentativo di accesso a Gestione unificata di SANtricity, esaminare queste possibili cause.

Gli errori di accesso a Unified Manager possono verificarsi per uno dei seguenti motivi:

* Il nome utente o la password immessi non sono corretti.
* Privilegi insufficienti.
* Il server di directory (se configurato) potrebbe non essere disponibile. In questo caso, provare ad accedere con un ruolo utente locale.
* Si è tentato di accedere più volte senza successo, attivando la modalità di blocco. Attendere 10 minuti per eseguire nuovamente l'accesso.


Gli errori di accesso a un array di storage remoto per le attività di mirroring possono verificarsi per uno dei seguenti motivi:

* La password immessa non è corretta.
* Si è tentato di accedere più volte senza successo, attivando la modalità di blocco. Attendere 10 minuti per effettuare nuovamente l'accesso.
* È stato raggiunto il numero massimo di connessioni client utilizzate sul controller. Verificare la presenza di più utenti o client.

