---
permalink: um-admin/administrator-password-protection-unified.html 
sidebar: sidebar 
keywords: configure, santricity, unified, manager, administrator, password, protect, unauthorized, access 
summary: È necessario configurare SANtricity Unified Manager con una password di amministratore per proteggerla da accessi non autorizzati. 
---
= Protezione con password di amministratore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario configurare SANtricity Unified Manager con una password di amministratore per proteggerla da accessi non autorizzati.



== Impostazione di una password amministratore

L'impostazione di una password di amministratore protegge il software dagli utenti che eseguono comandi distruttivi inconsapevolmente o maliziosamente. Quando si avvia Unified Manager per la prima volta, viene richiesto di impostare una password di amministratore.

Esiste una password di amministratore condivisa tra tutti gli utenti. Tutti gli utenti che dispongono di questa password possono apportare modifiche alla configurazione dei sistemi storage.



== Immissione della password

Il software richiede la password una sola volta durante una singola sessione di gestione. Per impostazione predefinita, una sessione scade dopo 30 minuti di inattività. A questo punto, è necessario immettere nuovamente la password. Se lo si desidera, è possibile regolare il timeout della sessione.

Se un altro utente accede al software da un altro client di gestione e modifica la password mentre la sessione è in corso, viene richiesta una password la volta successiva che si tenta di eseguire un'operazione di configurazione o un'operazione di visualizzazione.

Per motivi di sicurezza, è possibile tentare di inserire una password solo cinque volte prima che il software entri in uno stato di "blocco". In questo stato, il software rifiuta i successivi tentativi di immissione della password. Attendere 10 minuti per ripristinare lo stato "normale" prima di inserire nuovamente la password.
